export enum ALERT_HISTORY_STATUS {
  PENDING = 'PENDING',
  FIRING = 'FIRING',
  CONFIRMED = 'CONFIRMED',
  RECOVERED = 'RECOVERED',
}

export enum ALERT_LEVEL {
  NORMAL = 'NORMAL',
  CRITICAL = 'CRITICAL',
}
