// create data
export const USER_DATA_CREATE = 'CREATE_USER_DATA';
export const MENU_DATA_CREATE = 'CREATE_MENU_DATA';
export const ROUTE_DATA_CREATE = 'CREATE_ROUTE_DATA';
export const CONTAINER_LOADING_DATA_CREATE = 'CREATE_CONTAINER_LOADING_DATA';
export const CONTAINER_LOADED_DATA_CREATE = 'CREATE_CONTAINER_LOADED_DATA';
